### ISSUE TITLE
Make icons a11y compliant

### ISSUE THREAD

**Issue by hellofromtonya** [Getbeans/Beans#99]
Make the font icons a11y compliant by:

1. Change the `<i>` tag to `<span>`.
2. Ensure each has `aria-hidden="true"` attribute.
3. Add a `screen-reader-text` CSS block.
4. If the icon is semantic or interactive, add `<span class="screen-reader-text">Context given here.</span>`.

For the `.screen-reader-text` CSS, we can use:

```
.screen-reader-text {
	border: 0;
	clip: rect(0, 0, 0, 0);
	height: 1px;
	overflow: hidden;
	position: absolute !important;
	width: 1px;
	word-wrap: normal !important;
}
```

Examples:
- Visual cue <span class="fa fa-twitter" aria-hidden="true"></span>
- Semantic or interactive <span class="fa fa-twitter" aria-hidden="true"><span class="screen-reader-text">Follow us on Twitter</span></span>

For initial conversations between @christophherr and me, see the [closed issue #90](https://github.com/Getbeans/Beans/issues/90).

**Comment by christophherr** [comment]
Should we use the new screen-reader-text class from Core?

```css
.screen-reader-text {
    border: 0;
    clip: rect(1px, 1px, 1px, 1px);
    -webkit-clip-path: inset(50%);
    clip-path: inset(50%);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
    word-wrap: normal !important;
}
```

see: https://make.wordpress.org/core/2017/10/22/changes-to-the-screen-reader-text-css-class-in-wordpress-4-9/
